[package]
name = "sendgrid"
version = "0.5.3"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
description = "An unofficial client library for the SendGrid API"
repository = "https://github.com/gsquire/sendgrid-rs"
license = "MIT"
homepage = "https://sendgrid.com"
keywords = ["email"]
documentation = "https://docs.rs/sendgrid"

[dependencies]
data-encoding = "1.2"
hyper = "0.10"
hyper-native-tls = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.2"
