[package]
name = "sendgrid"
version = "0.2.0"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
description = "An unofficial client library for the SendGrid API"
repository = "https://github.com/gsquire/sendgrid-rs"
license = "MIT"
homepage = "https://sendgrid.com"
keywords = ["email"]
documentation = "https://gsquire.github.io/docs/rust/sendgrid"

[dependencies]
hyper = "0.8"
time = "0.1"
rustc-serialize = "0.3"

[[bin]]
name = "main"
doc = false
path = "src/main.rs"
