[package]
name = "sendgrid"
version = "0.3.0"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
description = "An unofficial client library for the SendGrid API"
repository = "https://github.com/gsquire/sendgrid-rs"
license = "MIT"
homepage = "https://sendgrid.com"
keywords = ["email"]
documentation = "https://gsquire.github.io/doc/sendgrid/sendgrid"

[dependencies]
hyper = "0.9"
rustc-serialize = "0.3"
url = "1.1.1"

[[bin]]
name = "main"
doc = false
path = "src/main.rs"
