[package]
name = "sendgrid"
version = "0.1.0"
authors = ["Garrett Squire <garrett.squire@sendgrid.com>"]
description = "An unofficial client library for the SendGrid API"
repository = "https://github.com/gsquire/sendgrid-rs"
license = "MIT"
homepage = "https://sendgrid.com"

[dependencies]
hyper = "0.6"
time = "0.1"
rustc-serialize = "0.3"
